- name: Install EPEL repository
  ansible.builtin.yum:
    name: epel-release
    state: present

- name: Manually download Remi's GPG key
  ansible.builtin.get_url:
   url: https://rpms.remirepo.net/RPM-GPG-KEY-remi
   dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-remi

- name: Import Remi's GPG key
  ansible.builtin.command:
    cmd: rpm --import https://rpms.remirepo.net/RPM-GPG-KEY-remi

- name: Install Remi's repository
  ansible.builtin.yum:
   name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
   state: present

- name: Enable Remi's Redis module
  ansible.builtin.command:
   cmd: dnf module enable redis:remi-6.2

- name: Install Redis
  ansible.builtin.yum:
    name: redis
    state: present

- name: Update the IP address
  ansible.builtin.replace:
    path: "{{item}}"
    regexp: "127.0.0.1"
    replace: "0.0.0.0"
  loop:
    - /etc/redis.conf

- name: Start redis
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: yes