- name: Install the nginx rpm from a remote repo
  ansible.builtin.dnf:
    name: 'https://rpms.remirepo.net/enterprise/remi-release-8.rpm'
    state: present
    
- name: Install Redis
  ansible.builtin.yum:
    name: redis
    state: present

- name: Update the IP address
  ansible.builtin.replace:
    path: "{{item}}"
    regexp: "127.0.0.1"
    replace: "0.0.0.0"
  loop:
    - /etc/redis.conf

- name: Start redis
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: yes