- name: Install required packages
  ansible.builtin.yum:
   name:
    - epel-release
    - yum-utils
   state: present

- name: Install Remi's repository
  ansible.builtin.yum:
   name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
   state: present

- name: Enable Remi's Redis module
  ansible.builtin.command:
    cmd: yum-config-manager --enable remi

- name: Install Redis
  ansible.builtin.yum:
    name: redis
    state: present

- name: Update the IP address
  ansible.builtin.replace:
    path: "{{item}}"
    regexp: "127.0.0.1"
    replace: "0.0.0.0"
  loop:
    - /etc/redis.conf

- name: Start redis
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: yes