- name: Copy mongobd repo
  ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/

- name: Install Mongodb
  ansible.builtin.yum:
      name: mongodb-mongosh
      state: installed


- name: Replace IP address
  ansible.builtin.replace:
      path:  /etc/mongod.conf
      regexp: 127.0.0.1
      replace: 0.0.0.0

- name: Start mongodb
  ansible.builtin.systemd:
      name: mongod
      state: restarted
      enabled: yes

- name: Download database scheme
  ansible.builtin.import_role:
      name: common
      tasks_from: download

- name: Load schema
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/{{item}}.js"
    idempotent: yes
  loop:
    - catalogue
    - users

