- name: Demo on loops
  hosts: localhost
  tasks:
    - name: Demo
      debug:
        msg:Hello,
---
- name: Demo on loops
  hosts: localhost
  tasks:
    - name: Print messages
      debug:
        msg: "Hello, {{ item }}!"
      loop:
        - Alice
        - Bob
        - Charlie
