- name: Variable on play level
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL ={{URL}}
##Note: variable on play level-all tasks can access
- name: Variable from file on play level
  hosts: all
  vars_files:
    - sampleya.yml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
       msg: URL ={{URL}}
##Note:Variable file on play level-all tasks can access
- name: Variable on tast level
  hosts: all
  tasks:
    - name: Print URL in task1
      ansible.builtin.debug:
        msg: URL ={{URL}}
      vars:
       URL: task1.example.com

    - name: Print URL in task2
      ansible.builtin.debug:
          msg: URL ={{URL}}
      vars:
       URL: task2.example.com
##Note: Variable in one task cannot be accessed by other tasks

- name: Varibale Precedence
  hosts: all
  vars:
    URL: play level variable
  vars_files:
    - sampleya.yml
  tasks:
    - name: task1
      ansible.builtin.debug:
        msg: URL ={{URL}}
      vars:
        URL: pp.com
