- name: Variable on play level
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL ={{URL}}
##Note: variable on play level can be accessed in all tasks
- name: Variable from file
  hosts: all
  vars_files:
    - sample-vars.yml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
       msg: URL ={{URL}}




