- name: Download and install packages
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: Setup and create app user
  ansible.builtin.import_role:
    name: common
    tasks_from: download

- name: Install {{COMPONENT}} dependencies
  ansible.builtin.pip:
    requirements: /home/roboshop/{{COMPONENT}}/requirements.txt
    executable: pip3

- name: print
  debug:
    msg: "{{appuser}}"