- name: Setup repo
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | sudo bash

- name: Install rabbitmq and erlang
  ansible.builtin.yum:
    - rabbitmq-server
    - https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | sudo bash
  state: installed

- name: start Rabbitmq server
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: setting usre permissions
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present
    tags:
      - administrator

