- name: Setup repo
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | sudo bash

- name: Add Erlang repository
  command: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | sudo

- name: Install RabbitMQ and Erlang
  yum:
    name:
      - rabbitmq-server
      - erlang
    state: present
    
- name: start Rabbitmq server
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: setting user permissions
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present
    tags:
      - administrator

