- name: Setup MySQL Repo
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Disable MySQL module
  shell: dnf module disable mysql

- name: Install MySQL Server
  ansible.builtin.yum:
    name:
      - mysql-community-server
    state: installed



