- name: Setup MySQL repository and disable MySQL module
  hosts: all
  become: yes
  tasks:
    - name: Download MySQL repo file
      get_url:
        url: https://raw.githubusercontent.com/roboshop-devops-project/mysql/main/mysql.repo
        dest: /etc/yum.repos.d/mysql.repo

    - name: Disable MySQL module
      command: dnf module disable mysql
