- name: Setup MySQL Repo
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Disable MySQL module
  command: dnf module disable mysql
  args:
     warn: false


- name: Install MySQL Server
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed
