- name: Copy mysql repo
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Disable MySQL module
  ansible.builtin.shell:
   cmd: dnf module disable mysql -y

- name: Install MySQL community server
  ansible.builtin.def:
    name: mysql-community-server
    state: present

- name: Start the service
  ansible.builtin.systemd:
    name: mysqld
    state: restarted
    enabled: true

- name: Check if password is expiring
  mysql_info:
     login_user: root
     login_password: RoboShop@1
     filter: databases

- name: Find the password
  ansible.builtin.shell: grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}'
  register: mysql_output

- name: Print
  debug:
    msg: "{{mysql_output}}"