- name: Download MySQL repo file
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Disable MySQL module
  shell: dnf module disable mysql -y

- name: Install MySQL server
  ansible.builtin.yum:
      name:
        - mysql-community-server
      state: present

- name : install
  ansible.builtin.pip:
    name: pymysql

- name: Start and enable MySQL service
  ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

- name: Check if new password is working
  mysql_info:
    login_user: root
    login_password: RoboShop@1
    filter: databases
  register: check_pass
  ignore_errors: yes

- name: Find
  ansible.builtin.shell: grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}'
  register: mysql_output
  when: check_pass.failed

- name: Password Change Block
  when: check_pass.failed
  block:
    - name: Find the temporary password
      ansible.builtin.shell: grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}'
      register: mysql_output

    - name: Copy Password Reset SQL
      ansible.builtin.template:
        src: passreset.sql
        dest: /tmp/pass.sql

    - name: Change Default password
      ansible.builtin.shell: mysql --connect-expired-password -uroot -p"{{mysql_output.stdout}}" </tmp/pass.sql

