- name: Setup MySQL Repo
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Disable MySQL module
  dnf_module:
   name: "@mysql"
   state: diabled

- name: Install MySQL Server
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed
