- name: Download MySQL repo file
  get_url:
    url: https://raw.githubusercontent.com/roboshop-devops-project/mysql/main/mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Disable MySQL module
  ansible.builtin.dnf:
     name: '@mysql-community'
     state: absent

- name: Install MySQL Server
  ansible.builtin.yum:
    name:
      - mysql-community-server
    state: installed



