---
- name: Setup MySQL Community Server
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Copy mysql repo
      ansible.builtin.copy:
        src: mysql.repo
        dest: /etc/yum.repos.d/mysql.repo

    - name: Disable MySQL module
      ansible.builtin.shell:
        cmd: dnf module disable mysql -y

    - name: Disable MySQL package
      ansible.builtin.dnf:
        name: mysql
        state: absent

    - name: Install mysql community
      ansible.builtin.yum:
        name: mysql-community-server
        state: installed

    - name: Install python3-PyMySQL
      ansible.builtin.yum:
        name: python3-PyMySQL
        state: present

    - name: Start the MySQL service
      ansible.builtin.systemd:
        name: mysqld
        state: restarted
        enabled: true

    - name: Check if password is expiring
      mysql_info:
        login_user: root
        login_password: RoboShop@1
        filter: databases
