- name: Setup MySQL Repo
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Remove mysql-server package
- ansible.builtin.dnf:
   name: mysql
   state: disabled

- name: Install MySQL Server
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed