- name: Download MySQL repo file
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Disable MySQL module
  shell: dnf module disable mysql -y

- name: Install MySQL server
  ansible.builtin.yum:
      name:
        - mysql-community-server
      state: present

- name : install
  ansible.builtin.pip:
    name: pymysql

- name: Start and enable MySQL service
  ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

- name: Check if new password is working
  mysql_info:
    login_user: root
    login_password: RoboShop@1
    filter: databases
    ignore_errors: yes
  register: check_pass

- name: print
  debug:
    msg: "{{check_pass}}"

- name: Find
  ansible.builtin.shell: grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}'
  register: mysql_output

- name: Print
  debug:
    msg: "{{ mysql_output}}"



