- name: Add Application user
  ansible.builtin.user:
    name: roboshop
    state: present

- name: Download the {{COMPONENT}} from git-hub and extract it
  unarchive:
    src: https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Clean old app code
  ansible.builtin.file:
    path: /home/roboshop/{{COMPONENT}}
    state: absent

- name: Copy app code
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}
    remote_src: yes
  become_user: roboshop

- name: setup app code
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd

