- name: Install Golang
  ansible.builtin.yum:
    name: golang
    state: installed

- name: setup app user and code
  ansible.builtin.import_role:
    name: common
    tasks_from: download

- name: Install {{COMPONENT}} dependencies
  ansible.builtin.shell:  go mod init dispatch && go get && go build
  args:
    chdir: /home/roboshop/{{COMPONENT}}
  become: yes
  become_user: roboshop

- name: Configure systemd {{COMPONENT}}
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd
