- name: Copy systemd service file
  template:
    src: systemd.service
    dest: /etc/systemd/system/mysql.service


- name: start {{COMPONENT}} service
  ansible.builtin.systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: yes
    daemon_reload: yes
